name: Continues Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: cd build/ && tar -cvf build.tar.gz *
      - name: Copy tar file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/build.tar.gz
          remote: /var/www/build.tar.gz
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Run untar on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/ && rm -rf ${{ secrets.FOLDER_NAME }} && mkdir ${{ secrets.FOLDER_NAME }} && tar -xvf build.tar.gz -C ${{ secrets.FOLDER_NAME }} && rm build.tar.gz
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
